# Generated by Django 3.0.4 on 2020-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200707_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
