# Generated by Django 2.2.14 on 2020-07-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_webusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webusers',
            name='location',
        ),
        migrations.RemoveField(
            model_name='webusers',
            name='phone',
        ),
        migrations.AddField(
            model_name='webusers',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='webusers',
            name='contactno',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='webusers',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='webusers',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
