# Generated by Django 2.2.14 on 2020-07-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200723_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webusers',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address'),
        ),
    ]
