# Generated by Django 3.0.4 on 2020-07-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
