# Generated by Django 2.2.14 on 2020-07-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rudrakshya', models.CharField(default='Rudrakshya', max_length=255)),
                ('Mala', models.CharField(default='Mala', max_length=255)),
                ('VastuYantra', models.CharField(default='Vastu Yantra', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_categories'),
        ),
    ]
