# Generated by Django 2.2.14 on 2020-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200716_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_categories',
            name='Rudrakshya',
            field=models.CharField(default='Rudrakshya', max_length=255),
        ),
    ]
