# Generated by Django 2.2.14 on 2020-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200716_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_categories',
            old_name='Rudrakshya',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product_categories',
            name='Mala',
        ),
        migrations.RemoveField(
            model_name='product_categories',
            name='VastuYantra',
        ),
        migrations.AddField(
            model_name='product_categories',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
