# Generated by Django 2.2.14 on 2020-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200716_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_categories',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_categories',
            name='slug',
            field=models.SlugField(default='one'),
        ),
    ]
