# Generated by Django 2.2.14 on 2020-07-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200717_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_categories',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_categories',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
