# Generated by Django 2.2.14 on 2020-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200719_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
