# Generated by Django 2.2.14 on 2020-07-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200719_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
