# Generated by Django 2.2.14 on 2020-08-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200720_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='original_price',
        ),
    ]
