# Generated by Django 2.2.14 on 2020-07-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope1',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horoscope1',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
