# Generated by Django 2.2.14 on 2020-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_horoscope1_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope1',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
